added compass-options as a dependency due to errors while running grunt
grunt watch

Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'compass-options'